# Answer to Qn no. 1

In [1]:
#Create a numpy array starting from 2 till 50 with a stepsize of 3.
import numpy
sample = numpy.array([i for i in range(2,50,3)])
print(sample)




[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [2]:
# sample 2 including 50
import numpy
sample2 = numpy.array([i for i in range(2,51,3)])
print(sample2)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


# Answer to Qn no. 2

In [5]:
import numpy
from numpy import concatenate, sort
a=[1,2,3,4]
b=[5,6,7,8]
c = concatenate((a,b))
c.sort(kind='mergesort') 
print(c.sort)

<built-in method sort of numpy.ndarray object at 0x00000237CA5D6C10>


In [4]:
import numpy as np

arr1 = np.array([input("Enter 5 elements of list 1 :") for i in range (5)])

arr2 = np.array([input("Enter 5 elements of list 2 :") for i in range (5)])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

Enter 5 elements of list 1 :2
Enter 5 elements of list 1 :4
Enter 5 elements of list 1 :5
Enter 5 elements of list 1 :6
Enter 5 elements of list 1 :7
Enter 5 elements of list 2 :1
Enter 5 elements of list 2 :2
Enter 5 elements of list 2 :3
Enter 5 elements of list 2 :4
Enter 5 elements of list 2 :5
[['2' '1']
 ['4' '2']
 ['5' '3']
 ['6' '4']
 ['7' '5']]


# Answer to Qn. No 3

In [9]:
#dimension of numpy array
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print(arr.shape)

(2, 3)


# Answer to Qn. No 4

In [11]:
# consider the one dimensional orray [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('1D Numpy array:')
print(arr)


1D Numpy array:
[0 1 2 3 4 5 6 7 8 9]


In [14]:
#we can convert this array into a 2D array by using "np.reshape(arr,(m,n))" operation, for example 
import numpy as np
np.reshape(arr,(2,5))


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# the output shows the rearranged form of ID array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
# into 2D array    array  ([[0, 1, 2, 3, 4],
#                         [5, 6, 7, 8, 9]])    

# Answer to Qn. No 5

In [57]:
import numpy as np


In [41]:
arr1 = np.array( [[ 0, 1 ],
                 [ 2, 3, ]] )
arr2 = np.array( [[ 4, 5 ],
                 [ 6, 7 ]] )

In [45]:
np.vstack((arr1,arr2))
np.hstack((arr1,arr2))

array([[0, 1, 4, 5],
       [2, 3, 6, 7]])

In [50]:
print("vspace function \n",np.vstack((arr1,arr2)),"\n hspace function \n",
np.hstack((arr1,arr2))
)

vspace function 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]] 
 hspace function 
 [[0 1 4 5]
 [2 3 6 7]]


# Answer to Qn. No 6

In [56]:
# Get unique values in a numpy array
arr = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)
# Get unique values from a numpy array
uniqueValues = np.unique(arr)
print('Unique Values : ',uniqueValues)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
